---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:

    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi mohamedrezk99/test
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t mohamedrezk99/test .

    - name: Push Image to dockerhub
      command: docker push mohamedrezk99/test

    - name: run container
      command: docker run -d --name web-container -p 5000:80 mohamedrezk99/test

